# Generated by Django 5.2.7 on 2025-10-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipo",
            name="categoria",
            field=models.CharField(max_length=100, verbose_name="Categoría"),
        ),
        migrations.AlterField(
            model_name="equipo",
            name="estado",
            field=models.CharField(max_length=100, verbose_name="Estado actual"),
        ),
        migrations.AlterField(
            model_name="equipo",
            name="fecha_ingreso",
            field=models.DateField(verbose_name="Fecha de ingreso"),
        ),
        migrations.AlterField(
            model_name="equipo",
            name="nombre",
            field=models.CharField(max_length=100, verbose_name="Nombre del equipo"),
        ),
        migrations.AlterField(
            model_name="equipo",
            name="ubicacion",
            field=models.CharField(max_length=100, verbose_name="Ubicación"),
        ),
    ]
